### PR TITLE
Added speed and course information to the traccar log. This would hel…

### PR DESCRIPTION
**Pull request by asatsi**
…p push this information readily into any other UI just showcasing the truck movement. And also would be handy to store it via logstash.

### CODE REVIEW

**Comment by tananaev** [comment]
You need to merge latest changes from master repository.

**Comment by asatsi** [comment]
It shows: "Able to merge" and also "This branch is 1 commit ahead of tananaev:master." I think the sources are up to date as master. Could you please let me know?

**Comment by tananaev** [comment]
There are no merge issues, but it reverts my change (61c54f16cf75d33923fc18b6abcee843f523dec2).

**Comment by tananaev** [comment]
Closing this as a duplicate.

**Pull request closed without merging**
