### PR TITLE
Added Lithuanian/Lietuvių l10n.

### PR DESCRIPTION
**Pull request by MRokas**
Added lt.js file, for localization.
Updated locale.js to allow app access lt l10n.

### CODE REVIEW

**Comment by tananaev** [comment]
Thanks for the pull request.

**Comment by MRokas** [comment]
No probs.!

Using open-source stuff without any contribution where possible is disrespect to _Glorious Open Source World_ in my opinion.

**Comment by tananaev** [comment]
I just noticed it and fixed the problem.

**Comment by tananaev** [comment]
@MRokas, I have decided to use Transifex platform to manage all Traccar translations. I would appreciate if you could register there as Lithuanian translator for Traccar project to keep translation up to date:

https://www.transifex.com/traccar/traccar

**Comment by MRokas** [comment]
Registered, and off to do some stuff there.

**Pull request merged**
