### PR TITLE
store valid position as latest

### PR DESCRIPTION
**Pull request by alisol911**

### CODE REVIEW

**Comment by tananaev** [comment]
This will not be merged if you don't provide any explanation.

**Comment by alisol911** [comment]
Invalid positions are used as event log only, we lost current position when latest is invalid

**Comment by tananaev** [comment]
I don't agree. Someone might be interested to see additional sensor information even if position is invalid.

**Comment by alisol911** [comment]
Ok, I handle this in my own branch, thanks

**Pull request closed without merging**
