### PR TITLE
Increase minimal token length

### PR DESCRIPTION
**Pull request by Abyss777**
To be consistent with web part

### CODE REVIEW

**Comment by tananaev** [comment]
I just though... what would happen to existing 16-character tokens?

**Comment by Abyss777** [comment]
Hm, you are right. User object won't be created from DB.

**Comment by tananaev** [comment]
I guess we should keep it as it is. There might be a way to deal with it,  but I don't want to make it too complicated.

**Comment by Abyss777** [comment]
Move validation to API resource.
But OK. Leave it as is.

**Pull request closed without merging**
