### PR TITLE
Update to EElink Decoder/Encoder

### PR DESCRIPTION
**Pull request by tsmgeek**
Supersedes #3420 due to correction of branches

### CODE REVIEW

**Comment by tananaev** [comment]
Please let me know when all the comments from the previous pull request are fixed, so I can review it.

**Comment by tsmgeek** [comment]
Remaining comments I am leaving as they are helpful.

**Comment by tananaev** [comment]
You are free to leave it of course, but in that case unfortunately it's not going to be merged. Let me know if you decide to change your mind.

**Comment by tsmgeek** [comment]
Why do you have such a big problem with comments?
It seems a form of protectionism to keep things obscure.

**Comment by tananaev** [comment]
I don't like unnecessary code and duplication. It always results in inconsistency and maintenance headache in the long term.

**Comment by tsmgeek** [comment]
That is an excuse, never heard anyone saying something is a maintenance headache when there are some comments, bad code yes. I understand if someone did a massive commit with silly things like `woops why are we here` etc but this is not the case. Its a protocol decoder not voodoo.

**Pull request closed without merging**
