### PR TITLE
MaxError despite Valid mark

### PR DESCRIPTION
**Pull request by 5of9**
I get every day jumps over 4000km because the tracker sends valid mark despite it sends useless coordinates, I already set coordinatesMaxError, but now  I see this only works when the position is not valid, isn't it? So I think it would be better to have another way to see if its a tracker error or a tracker flown in a plane or so!? What do you think?

### CODE REVIEW

**Comment by 5of9** [comment]
Maybe they should also implement a check, if the coordinates are valid and set to invalid by server when it gets coordinates with 300 degrees or so... Server should be more intelligent than those stupid trackers... :)

**Comment by tananaev** [comment]
There is already `filter.maxSpeed` option available to filter out jumps like that.

**Comment by 5of9** [comment]
Thank you, I was so fixed on the distance, so I didn't even read the Speedfilter in the source. But what do you think about a filter.nonEarth which filters positions over 90 and 180 degrees, which doesn't exist on earth?
How can I help you with the https://www.traccar.org/configuration-file/ to add speedfilter and some other things?

**Comment by tananaev** [comment]
I don't think it's necessary. Do you have a device that sends data over 90/180 degress?

**Comment by 5of9** [comment]
Yes. The TK5000 does sometimes...

**Comment by tananaev** [comment]
Then it can be a part of "valid" filtering.

**Comment by 5of9** [comment]
I'll do so. Closed because this is not nessesary

**Pull request closed without merging**
