### PR TITLE
Date/Time Improvements

### PR DESCRIPTION
**Pull request by jon-stumpf**
I introduced a new function in the Parser class, nextDateTime().  This allowed me to eliminate duplicative code in many protocols.  I also found some discrepancies in the comments for dates and time which I cleared up.  I still have some anomalies that I am chasing and will raise issues to determine if these need to be fixed.

### CODE REVIEW

**Comment by tananaev** [comment]
I don't like the massive enum and switch case. I think it would be better to use a few booleans instead. For example `dateFirst`, `dateReverse`, `hasMillis`. That should cover most of the cases. For weird places where we have only time, we can use existing code as it's only 1-2 lines anyway.

**Comment by jon-stumpf** [comment]
Removed millisecond information from three protocols as per discussion in Issue #2995.

**Comment by tananaev** [comment]
Checks are failing and there are merge conflicts.

**Comment by jon-stumpf** [comment]
Sorry.  I got interrupted.  I have updated the branch.

**Comment by tananaev** [comment]
Still conflicts.

**Comment by jon-stumpf** [comment]
Just undid my work on the StarLink protocol to resolve a merge conflict.

**Comment by jon-stumpf** [comment]
I did not know how to remove the merge so I closed this Pull Request and opened a new one, finishing the last revisions that you requested.

**Pull request closed without merging**
