### PR TITLE
Add support to authorization basic http header in alternative to…

### PR DESCRIPTION
**Pull request by guterresrafael**
…cookie and java session.
Modification to allow traccar api stateless.

### CODE REVIEW

**Comment by tananaev** [comment]
Can you please run `mvn site` and fix any reported code issues in your code if there are any. Otherwise it looks good.

**Comment by tananaev** [comment]
Thanks for the pull request. I have merged the changes.

**Comment by ulion** [comment]
when using http auth, how to disable session manager so it won't create new session for all such stateless requests?

**Comment by tananaev** [comment]
You can just remove `setSessionManager` call.

**Comment by ulion** [comment]
In old version of traccar server, there is no setSessionManager call, but
it has still some web server internal default session manager.

so, it does not do it, any better idea?

2016-04-11 9:33 GMT+08:00 Anton Tananaev <notifications@github.com>:

> You can just remove setSessionManager call.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/pull/1510#issuecomment-208112032>
>



-- 
Ulion

**Comment by tananaev** [comment]
Try to change `ServletContextHandler.SESSIONS` to `ServletContextHandler.NO_SESSIONS`.

**Comment by ulion** [comment]
Thx.

**Pull request merged**
