### PR TITLE
Move device id to a session

### PR DESCRIPTION
**Pull request by tananaev**
Changed `BaseProtocolDecoder` class to store device id in a session.

This solves potential problem with UDP connections.

@Abyss777, can you please take a quick look. There are a lot of changes and I don't trust myself to not make any silly mistakes there. Also, I think now we can store position sequence id in the session. That was the main purpose of this refactoring.

### CODE REVIEW

**Comment by Abyss777** [comment]
I've found a problem.  Devices never become offline.
You removed `Context.getConnectionManager().addActiveDevice` because of that https://github.com/tananaev/traccar/blob/master/src/org/traccar/database/ConnectionManager.java#L56 will never set `DEVICE_OFFLINE`

**Comment by tananaev** [comment]
Fixed the problem. Thanks.

Have you finished the review? Is there anything else?

**Comment by Abyss777** [comment]
Other seems OK, but...
I'm thinking of another thing. What happen if there is short tcp connection lost, and device will try to reconnect while previous session still active. Will it be replaced? I do not see that, looks like old session will be returned. Or am I wrong?

**Comment by Abyss777** [comment]
I'm wrong. There will be a new instance of Decoder and new instance of session.
Everything is OK.

**Comment by tananaev** [comment]
Merged. Thanks for reviewing the code.

**Pull request merged**
