### PR TITLE
Move lastPosition update to the end of pipeline

### PR DESCRIPTION
**Pull request by Abyss777**
- Optimize MotionEventHandler to do not use Device.motion
- Remove Device.motion from model and database
- some optimizations

### CODE REVIEW

**Comment by tananaev** [comment]
One thing unrelated to this pull request, but I just noticed it now. There is an extra space in `SPEED_THRESHOLD` variable definition. Please fix.

**Comment by tananaev** [comment]
Pull request looks fine. Can we remove status as well?

**Comment by Abyss777** [comment]
Space fixed.
Yes, we can. Should I do it here, or in other pull request?

**Comment by tananaev** [comment]
Let's do another pull request for it. Thanks

**Pull request merged**
