### PR TITLE
Revert GranitFrameDecoder

### PR DESCRIPTION
**Pull request by Abyss777**
`LineBasedFrameDecoder` did not fit at all, It handles both \n and \r\n. 0x0a appears rather frequently in binary data.
`DelimiterBasedFrameDecoder` is better but we can't exclude appearing 0x0d0a in binary data, for example I can set deviceId to 2537 and never handle any position. 

Because of that I've added reading frame based on `length` field of packet. Not binary packets handled as usual with \r\n delimiter.

### CODE REVIEW

**Comment by tananaev** [comment]
This all looks very messy. I read the documentation again and I suggest following algorithm for frame decoder:

1. Find end of line index
2. Try to find '~' index
3. If end of line comes first, return result
3. If symbol '~' comes before end of line, read length of binary data (length field comest right after '~'), go to point 1 and search from the end of binary data

Also, please add frame decoder unit tests.

**Comment by tananaev** [comment]
I also took another look at the protocol decoder, and it seems incorrect that you convert the whole message into a string even if it has binary data it in. Can't you just convert the header?

This check is definitely incorrect:
```java
bufString.contains("OK")
```
Binary data can contain anything including these two symbols.

**Comment by Abyss777** [comment]
I hurried, I'm sorry.
I've got your point about tilde, It is sign of binary data. I've done almost as you said.

To ProtocolDecoder...
with `bufString.contains("OK")` I wanted to cover cases `ACCESS OK` and `ERASE OK`
Header length can be less 6, `OK` is 2, `ERROR` is 5. But I agree something should be done with it.

**Comment by tananaev** [comment]
Merged, thanks. Please send me another pull request if you manage to fix issues in decoder.

**Pull request merged**
