### PR TITLE
Update swagger.json with recent changes

### PR DESCRIPTION
**Pull request by Abyss777**
Looks like forget nothing since 3.7 release

### CODE REVIEW

**Comment by tananaev** [comment]
Merged, thanks.

Sorry for off-topic, but did you have any problems with submodule? Just want some feedback if it's easier to use than completely separate repo.

**Comment by Abyss777** [comment]
I did not have any problems. But I do not see much benefits. They are only for newbie or people who just want to compile (not to do a pull-requests).

Man who want to contribute have to fork both repositories and add "remote" anyway. Even there is one additional action: rename your "origin" to "upstream". I mean contributors will treat them as two repositories anyway.

**Comment by tananaev** [comment]
It's very handy with IntelliJ. It automatically keeps both repos in sync. With two separate repositories it's more complicated.

**Comment by Abyss777** [comment]
I will work more with it. May be I did not noticed all benefits.

**Pull request merged**
