### PR TITLE
Set status to offline for new device

### PR DESCRIPTION
**Pull request by Abyss777**
I'm working on filtering in web-part discussed in #3025 

By default new device will have `""` as status and handle fourth value (empty string) is very very inconvenient and break logic.

### CODE REVIEW

**Comment by tananaev** [comment]
I think it's better to initialize it in the Device model.

**Comment by Abyss777** [comment]
You are right. Much better. Looks inverted but just not check for `null`

**Comment by tananaev** [comment]
Actually that's not what I had in mind. I thought just making it a default value for the instance variable would be enough.

**Comment by Abyss777** [comment]
Not really, it still be `""` when create device from web client

**Comment by tananaev** [comment]
Are you sure? Does the web app send empty status?

**Comment by Abyss777** [comment]
Yes.
Request
image

Response 
image

**Comment by tananaev** [comment]
This doesn't seem right. Same for other empty strings as well. Maybe there is a way to tell extjs to not send or send `null` if it's not set?

**Comment by Abyss777** [comment]
Agree, that it is not right, I'll try to find the solution from ExtJS side.
I was thinking... It is still not good to allow change Status via API...

**Comment by Abyss777** [comment]
It did not help.
Initialized on server side:
````java
private String status = STATUS_OFFLINE;
````
I used http://docs.sencha.com/extjs/6.2.0/classic/Ext.data.field.String.html#cfg-allowNull on the web side
And got the `null` in response
image

Looks like API explicitly set all incoming values then constructs entity

**Comment by tananaev** [comment]
OK, then I think instead of changing setter, we should change getter to something like this:
```java
return status != null : status : STATUS_OFFLINE;
```

**Comment by tananaev** [comment]
Merged, thanks.

**Pull request merged**
