### PR TITLE
Fix mail template encoding

### LINKED ISSUE #2772: Email notification template localization
Hi Anton

I have a question;
How can I get email notification in my language(Serbian)
I tried to modify template >online device

#set($subject = "$device.name: na mreži")    <----- online on serbian is > na mreži

<!DOCTYPE html>
<html>
<body>
Uređaj: $device.name<br>
Na mreži<br>
Vreme: $event.serverTime<br>
Link: <a href="$webUrl?eventId=$event.id">$webUrl?eventId=$event.id</a>
</body>
</html> 

result is when I get email

**UreÄ‘aj: Gosafe
Na mre\u009Ei
Vreme: Tue Jan 10 12:48:43 CET 2017**
Link: it is OK**

it should be 

****Uređaj: Gosafe
Na mreži
Vreme: Tue Jan 10 12:48:43 CET 2017**
Link: ok**

non ASCII characters shows as odd characters

**How can I modify template to get correct characters in Serbian when I get email ?**

thank you in advance

### PR DESCRIPTION
**Pull request by Abyss777**
fix #2772

### CODE REVIEW

**Comment by Abyss777** [comment]
I just thought may be better use `StandardCharsets.UTF_8.name()` instead?

**Comment by tananaev** [comment]
Yes, I think using constant is a better option.

**Comment by Abyss777** [comment]
Replaced commit with StandardCharset constant

**Comment by tananaev** [comment]
Merged, thanks.

**Pull request merged**
