### PR TITLE
Add switch to enable media web access

### PR DESCRIPTION
**Pull request by Abyss777**
Added switch `media.web.enable` and renamed `media.web.directoryAllow` for consistence

### CODE REVIEW

**Comment by tananaev** [comment]
Can you please also implement it for `MediaManager`.

**Comment by Abyss777** [comment]
Sure. Which values we will place in `/setup/default.xml`

**Comment by tananaev** [comment]
Enable by default. Maybe we should just enable it if path is provided?

**Comment by Abyss777** [comment]
Agree, extra parameters are useless.

**Comment by Abyss777** [comment]
Now protocols do not handle case when MediaManager is not defined. How does traccar should behave in case `MediaManager` disabled but got photo? Still create position from last and put something in attributes to inform what photo was skipped or silently skip them?

**Comment by tananaev** [comment]
Just return null and attribute will be zero. I don't think there is any problem with it.

**Comment by Abyss777** [comment]
Used `media.path` as switch and added handles when `MediaManager` is undefined in protocols.

**Comment by tananaev** [comment]
I was thinking of returning null from `writeFile` to avoid null checks.

**Comment by Abyss777** [comment]
But MediaManager might be not initialized https://github.com/tananaev/traccar/blob/master/src/org/traccar/Context.java#L340

**Comment by tananaev** [comment]
Yes, but maybe it's better to initialize it and then just return `null` if path is not specified. This way we won't need all those null checks.

**Comment by Abyss777** [comment]
Done

**Comment by tananaev** [comment]
Merged, thanks.

**Comment by tananaev** [comment]
I actually decided to revert back parameter name to the original one because now we use it in a single place and it makes much more sense: https://github.com/tananaev/traccar/commit/654116f06161a6f73d23a6bb610f5420cebfdfc9.

Sorry about that.

**Comment by Abyss777** [comment]
Thank you. It's OK.

**Pull request merged**
