### PR TITLE
Add support for OpenGTS compatible clients (GPSLogger for Android)

### PR DESCRIPTION
**Pull request by vblack**
Signed-off-by: Kostiantyn Luzan <vblack2006@gmail.com>

### CODE REVIEW

**Comment by tananaev** [comment]
Please rename classes from "OpenGTS" to "OpenGts". That's the coding style that we use.

Looks like it's an HTTP-based protocol. Why are you decoding it as a raw TCP protocol?

Do you have proper documentation for the format?

**Comment by vblack** [comment]
Ok, I will rename - not a problem.
Yes it is actually HTTP GET requests, but I am no familiar with your system, I just see that Sanav protocol did similar things, that needed for this.
Unfortunately I do not have documentation, however OpenGTS is opensource, so there should be something at least in the code.

**Comment by tananaev** [comment]
You need to take OsmAnd protocol as an example. It's also http-based.

**Comment by vblack** [comment]
Ok. I'll rework it based on OsmAnd

**Pull request closed without merging**
