### PR TITLE
Add lib for Microsoft JDBC Drivers with maven

### PR DESCRIPTION
**Pull request by CVSz**
[INFO] Copying mssql-jdbc-6.1.0.jre8.jar to /root/traccar/target/lib/mssql-jdbc-6.1.0.jre8.jar

sample config for mssql

```
<entry key='database.driverFile'>lib/mssql-jdbc-6.1.0.jre8.jar</entry>
<entry key='database.driver'>com.microsoft.sqlserver.jdbc.SQLServerDriver</entry>
<entry key='database.url'>jdbc:sqlserver://[serverName][\instanceName];user=[userName];password=[password];databaseName=[database];</entry>
<entry key='database.user'>[userName]</entry>
<entry key='database.password'>[password]</entry>
```

### CODE REVIEW

**Comment by tananaev** [comment]
I think we should be using JRE7 version.

Can we please get some confirmation from microsoft that it's allow to include it in installation package?

**Comment by CVSz** [comment]
after get some confirmation from microsoft i tell you again for merge

**Comment by CVSz** [comment]
dear, anton 
today i see news for mssql in ubuntu lol

https://docs.microsoft.com/th-th/sql/linux/sql-server-linux-setup-ubuntu

sure can install on Ubuntu 16.10 on my test server 

```
root@office:~# curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   983  100   983    0     0    460      0  0:00:02  0:00:02 --:--:--   461
OK
root@office:~# curl https://packages.microsoft.com/config/ubuntu/16.04/mssql-server.list > /etc/apt/sources.list.d/mssql-server.list
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    87  100    87    0     0    155      0 --:--:-- --:--:-- --:--:--   155
root@office:~# sudo apt-get update
Hit:1 http://th.archive.ubuntu.com/ubuntu yakkety InRelease
Get:2 http://th.archive.ubuntu.com/ubuntu yakkety-updates InRelease [94.5 kB]
Hit:3 http://th.archive.ubuntu.com/ubuntu yakkety-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu yakkety-security InRelease [93.3 kB]
Get:5 http://ppa.launchpad.net/webupd8team/java/ubuntu yakkety InRelease [17.6 kB]
Get:6 https://packages.microsoft.com/ubuntu/16.04/mssql-server xenial InRelease [2,828 B]
Get:7 http://th.archive.ubuntu.com/ubuntu yakkety-updates/main amd64 Packages [77.0 kB]
Get:8 http://th.archive.ubuntu.com/ubuntu yakkety-updates/universe i386 Packages [35.0 kB]
Get:9 http://th.archive.ubuntu.com/ubuntu yakkety-updates/universe amd64 Packages [35.0 kB]
Get:10 https://packages.microsoft.com/ubuntu/16.04/mssql-server xenial/main amd64 Packages [940 B]
Fetched 356 kB in 4s (73.0 kB/s)
Reading package lists... Done
root@office:~# sudo apt-get install -y mssql-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  authbind libcommons-collections3-java libcommons-dbcp-java libcommons-pool-java libecj-java libtomcat7-java tomcat7-common
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  gdb gdbserver libbabeltrace-ctf1 libbabeltrace1 libc++1 libc6-dbg libcc1-0 libcurl3 libdw1 libjemalloc1 libunwind8
Suggested packages:
  gdb-doc clang
The following NEW packages will be installed:
  gdb gdbserver libbabeltrace-ctf1 libbabeltrace1 libc++1 libc6-dbg libcc1-0 libcurl3 libdw1 libjemalloc1 libunwind8 mssql-server
0 upgraded, 12 newly installed, 0 to remove and 0 not upgraded.
Need to get 152 MB of archives.
After this operation, 728 MB of additional disk space will be used.
Get:1 http://th.archive.ubuntu.com/ubuntu yakkety/main amd64 libbabeltrace1 amd64 1.4.0-3 [34.9 kB]
Get:2 http://th.archive.ubuntu.com/ubuntu yakkety/main amd64 libdw1 amd64 0.166-2ubuntu1 [191 kB]
Get:3 http://th.archive.ubuntu.com/ubuntu yakkety/main amd64 libbabeltrace-ctf1 amd64 1.4.0-3 [99.0 kB]
Get:4 http://th.archive.ubuntu.com/ubuntu yakkety/main amd64 gdb amd64 7.11.90.20161005-0ubuntu1 [2,652 kB]
Get:5 https://packages.microsoft.com/ubuntu/16.04/mssql-server xenial/main amd64 mssql-server amd64 14.0.1.246-6 [144 MB]
Get:6 http://th.archive.ubuntu.com/ubuntu yakkety/main amd64 gdbserver amd64 7.11.90.20161005-0ubuntu1 [217 kB]
Get:7 http://th.archive.ubuntu.com/ubuntu yakkety/main amd64 libcc1-0 amd64 6.2.0-5ubuntu12 [31.1 kB]
Get:8 http://th.archive.ubuntu.com/ubuntu yakkety-updates/main amd64 libcurl3 amd64 7.50.1-1ubuntu1.1 [190 kB]
Get:9 http://th.archive.ubuntu.com/ubuntu yakkety/main amd64 libunwind8 amd64 1.1-4.1ubuntu2 [46.3 kB]
Get:10 http://th.archive.ubuntu.com/ubuntu yakkety/universe amd64 libc++1 amd64 3.7.0-1 [226 kB]
Get:11 http://th.archive.ubuntu.com/ubuntu yakkety/main amd64 libc6-dbg amd64 2.24-3ubuntu1 [4,547 kB]
Get:12 http://th.archive.ubuntu.com/ubuntu yakkety/universe amd64 libjemalloc1 amd64 3.6.0-9ubuntu1 [78.9 kB]
Fetched 152 MB in 36s (4,192 kB/s)
Preconfiguring packages ...
Selecting previously unselected package libbabeltrace1:amd64.
(Reading database ... 174683 files and directories currently installed.)
Preparing to unpack .../00-libbabeltrace1_1.4.0-3_amd64.deb ...
Unpacking libbabeltrace1:amd64 (1.4.0-3) ...
Selecting previously unselected package libdw1:amd64.
Preparing to unpack .../01-libdw1_0.166-2ubuntu1_amd64.deb ...
Unpacking libdw1:amd64 (0.166-2ubuntu1) ...
Selecting previously unselected package libbabeltrace-ctf1:amd64.
Preparing to unpack .../02-libbabeltrace-ctf1_1.4.0-3_amd64.deb ...
Unpacking libbabeltrace-ctf1:amd64 (1.4.0-3) ...
Selecting previously unselected package gdb.
Preparing to unpack .../03-gdb_7.11.90.20161005-0ubuntu1_amd64.deb ...
Unpacking gdb (7.11.90.20161005-0ubuntu1) ...
Selecting previously unselected package gdbserver.
Preparing to unpack .../04-gdbserver_7.11.90.20161005-0ubuntu1_amd64.deb ...
Unpacking gdbserver (7.11.90.20161005-0ubuntu1) ...
Selecting previously unselected package libcc1-0:amd64.
Preparing to unpack .../05-libcc1-0_6.2.0-5ubuntu12_amd64.deb ...
Unpacking libcc1-0:amd64 (6.2.0-5ubuntu12) ...
Selecting previously unselected package libcurl3:amd64.
Preparing to unpack .../06-libcurl3_7.50.1-1ubuntu1.1_amd64.deb ...
Unpacking libcurl3:amd64 (7.50.1-1ubuntu1.1) ...
Selecting previously unselected package libunwind8.
Preparing to unpack .../07-libunwind8_1.1-4.1ubuntu2_amd64.deb ...
Unpacking libunwind8 (1.1-4.1ubuntu2) ...
Selecting previously unselected package libc++1:amd64.
Preparing to unpack .../08-libc++1_3.7.0-1_amd64.deb ...
Unpacking libc++1:amd64 (3.7.0-1) ...
Selecting previously unselected package libc6-dbg:amd64.
Preparing to unpack .../09-libc6-dbg_2.24-3ubuntu1_amd64.deb ...
Unpacking libc6-dbg:amd64 (2.24-3ubuntu1) ...
Selecting previously unselected package libjemalloc1.
Preparing to unpack .../10-libjemalloc1_3.6.0-9ubuntu1_amd64.deb ...
Unpacking libjemalloc1 (3.6.0-9ubuntu1) ...
Selecting previously unselected package mssql-server.
Preparing to unpack .../11-mssql-server_14.0.1.246-6_amd64.deb ...
Unpacking mssql-server (14.0.1.246-6) ...
Setting up libcc1-0:amd64 (6.2.0-5ubuntu12) ...
Setting up libc6-dbg:amd64 (2.24-3ubuntu1) ...
Setting up libdw1:amd64 (0.166-2ubuntu1) ...
Setting up libjemalloc1 (3.6.0-9ubuntu1) ...
Setting up libcurl3:amd64 (7.50.1-1ubuntu1.1) ...
Setting up libunwind8 (1.1-4.1ubuntu2) ...
Processing triggers for libc-bin (2.24-3ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up gdbserver (7.11.90.20161005-0ubuntu1) ...
Setting up libbabeltrace1:amd64 (1.4.0-3) ...
Setting up libc++1:amd64 (3.7.0-1) ...
Setting up libbabeltrace-ctf1:amd64 (1.4.0-3) ...
Setting up gdb (7.11.90.20161005-0ubuntu1) ...
Setting up mssql-server (14.0.1.246-6) ...

+-------------------------------------------------------------------+
| Please run /opt/mssql/bin/sqlservr-setup to complete the setup of |
|                  Microsoft(R) SQL Server(R).                      |
+-------------------------------------------------------------------+

Processing triggers for libc-bin (2.24-3ubuntu1) ...
root@office:~# /opt/mssql/bin/sqlservr-setup
Microsoft(R) SQL Server(R) Setup

You can abort setup at anytime by pressing Ctrl-C. Start this program
with the --help option for information about running it in unattended
mode.

The license terms for this product can be downloaded from
http://go.microsoft.com/fwlink/?LinkId=746388 and found
in /usr/share/doc/mssql-server/LICENSE.TXT.

Do you accept the license terms? If so, please type "YES": yes

Please enter a password for the system administrator (SA) account:
The specified password does not meet SQL Server password policy requirements
because it is not complex enough. The password must be at least 8 characters
long and contain characters from three of the following five sets: uppercase
letters, lowercase letters, numbers, non-alphanumeric characters, or unicode
characters that are categorized as alphabetic characters, but are not
uppercase or lowercase.

Please enter a password for the system administrator (SA) account:
Please confirm the password for the system administrator (SA) account:

Setting system administrator (SA) account password...

Do you wish to start the SQL Server service now? [y/n]: y
Do you wish to enable SQL Server to start on boot? [y/n]: y
Created symlink /etc/systemd/system/multi-user.target.wants/mssql-server.service → /lib/systemd/system/mssql-server.service.
Created symlink /etc/systemd/system/multi-user.target.wants/mssql-server-telemetry.service → /lib/systemd/system/mssql-server-telemetry.service.

Setup completed successfully.

```

**Comment by tananaev** [comment]
I read news this morning as well. I think Microsoft is going in the right direction.

**Comment by tananaev** [comment]
More interesting news from Microsoft:

https://blogs.msdn.microsoft.com/jdbcteam/2016/11/17/open-source-jdbc-maven/

**Comment by CVSz** [comment]
now we can used with in maven ?

**Comment by tananaev** [comment]
I believe so. Merged.

**Pull request merged**
