### PR TITLE
removing double quotes

### PR DESCRIPTION
**Pull request by al3x1s**
got this warning if it has double quotes

======
2015-06-10 17:41:00  WARN: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"SELECT userId, deviceId FROM user_device;"' at line 1 - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException (NativeConstructorAccessorImpl.java:-2)

### CODE REVIEW

**Comment by tananaev** [comment]
I have reverted the merge because it has some other changes as well.

**Comment by al3x1s** [comment]
wow, sorry Anton, I just make some change in my fork after that commit, I did not know it would affect the pull request

**Comment by tananaev** [comment]
Please create another pull request.

**Comment by al3x1s** [comment]
ok, I already did it

**Pull request merged**
