### PR TITLE
Use queryParam instead of pathParam

### PR DESCRIPTION
**Pull request by Abyss777**
It will fit more to REST

https://github.com/tananaev/traccar-web/pull/347 relies on this

### CODE REVIEW

**Comment by tananaev** [comment]
I don't agree with this. Path parameter fits REST much better. We use query param for positions only because we want to request multiple positions at the same time. Looks like we don't need it in this case.

**Comment by Abyss777** [comment]
OK. I was confused that we retrieve objects with GET without id in path everywhere.

**Comment by tananaev** [comment]
The idea is that GET without id gives a collection of objects. GET with id gives a single object. Ideally for positions we should be using path as well, but I guess to optimize it a little bit we decided to request all positions in one request, so we use query parameter. So, it's more an exception than a rule.

**Comment by Abyss777** [comment]
I see. And yes, at first, I've tried do get every position in separate request. It was very inconvenient.

**Pull request closed without merging**
