### PR TITLE
Small fix in french I10n

### PR DESCRIPTION
**Pull request by vsurrel**

### CODE REVIEW

**Comment by tananaev** [comment]
Localization is manager using Transifex. Please submit your fix there:

https://www.transifex.com/traccar/traccar/

**Comment by renaudallard** [comment]
I have corrected those in Transifex and i also corrected some more small mistakes.

**Comment by tananaev** [comment]
Thanks. All the fixes will be included in the next release.

**Comment by renaudallard** [comment]
I also translated traccar manager and finished the translation of traccar android client

**Comment by tananaev** [comment]
Those will be updated with corresponding releases as well.

**Pull request closed without merging**
