### PR TITLE
Minifinder CUSTOM commands

### PR DESCRIPTION
**Pull request by hanselsen**
Hi Anton

I've been fiddling with the code and I think I've managed to implement the custom commands correctly, although not entirely seamless.

I added a MiniFinderEncoder, which extracts the raw string from the command. However, since I cannot seem to enter anything but integers in the values of the attributes, I used the command as the key. (hoping you can provide a better solution).

I've tested it with the following command in JSON:
```
{
    "deviceId":1,
    "type":"CUSTOM",
    "attributes": {
        "M,700":1
    }
}
```

I also create a test for it, hope that's OK?

### CODE REVIEW

**Comment by tananaev** [comment]
You should be able to use String as a value.

**Comment by hanselsen** [comment]
I should right? It is throwing a JacksonSomethingException that the value
could not be parsed to an Integer.

Op za 13 feb. 2016 21:58 schreef Anton Tananaev <notifications@github.com>:

**Comment by tananaev** [comment]
Can you show me what you send?

**Comment by hanselsen** [comment]
Sorry for all this. I really get confused when I use the UI mod. The code
is not failing at all. Given the changes I made, it fits perfectly when I
send the command in JSON format. Ill push my changes so that you can add
"raw" as attribute with the textual command as value.


Op zo 14 feb. 2016 09:09 schreef Anton Tananaev <notifications@github.com>:

**Comment by tananaev** [comment]
Please push new changes to the pull request. Also, can you please rename `CUSTOM` into `TYPE_CUSTOM` to be more clear what it's for.

**Comment by hanselsen** [comment]
I've pushed my changes to the branche :)

Op zo 14 feb. 2016 om 21:24 schreef Anton Tananaev <notifications@github.com

**Comment by hanselsen** [comment]
@tananaev was this merge request successfully integrated?

**Comment by tananaev** [comment]
Merged. Thanks for the pull request.

**Comment by hanselsen** [comment]
Thank you for the merge!

Op za 12 mrt. 2016 07:43 schreef Anton Tananaev <notifications@github.com>:

**Pull request merged**
