### PR TITLE
Fix connection check sql

### PR DESCRIPTION
**Pull request by drecchia**

### CODE REVIEW

**Comment by tananaev** [comment]
Please use spaces instead of tabs.

**Comment by tananaev** [comment]
Do we need to call `setConnectionInitSql`? Or is it optional?

**Comment by drecchia** [comment]
It defines the behavior to test the retrieved connection, If you remove, you wont have the feature.

**Comment by tananaev** [comment]
How about we define `SELECT 1;` as a default value (second parameter in `config.getString`), so we don't need to define it in every config. But it would still be possible to override it if required.

**Pull request merged**
