### PR TITLE
Put the html code for degree instead of the special character

### PR DESCRIPTION
**Pull request by renaudallard**
This causes display issues in some mail clients

### CODE REVIEW

**Comment by renaudallard** [comment]
Actually, putting the following header could probably also solve the issue, but I have not tested that.
`Content-Transfer-Encoding: 8bit`

I think the issue is because we currently have a charset of 8 bits with a transfer encoding of 7 bits.
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

**Comment by renaudallard** [comment]
Encoding in base64 might even be cleaner

**Comment by tananaev** [comment]
Does this work will all email clients?

@Abyss777, can you have a quick look to see if there are any potential issues.

**Comment by renaudallard** [comment]
It works with at least thunderbird, macos mail, rainloop.

**Comment by Abyss777** [comment]
@tananaev checked it, no issues.
It is really more correct way for degree sign in html.

**Comment by tananaev** [comment]
Merged, thanks @renaudallard for pull request and thanks @Abyss777 for reviewing the change.

**Pull request merged**
