### PR TITLE
Extend device model with management info

### PR DESCRIPTION
**Pull request by Abyss777**
As discussed in #2316

### CODE REVIEW

**Comment by renaudallard** [comment]
What's the difference between model and type?

**Comment by Abyss777** [comment]
Model is «Wonde Proud M7» or «Teltonika FM1100». Type is «truck» or «plane» or «yacht».

**Comment by renaudallard** [comment]
Wouldn't something like "conveyor" be more explicit than "type"? I hardly find a better word to be honest.

**Comment by renaudallard** [comment]
It would be nice to add the SIM number and SIM provider too.

**Comment by tananaev** [comment]
I guess we can use "class" or "category" instead of "type", to make it more clear that it's the object type, not device type. @Abyss777, what do you think?

SIM number is the phone number, so it's already there.

**Comment by renaudallard** [comment]
By SIM number, I meant the ICCID. Just like the phone number or contact or category, it's handy to have it there.

**Comment by tananaev** [comment]
That can definitely go into device attributes. We don't need a separate column for it.

**Comment by Abyss777** [comment]
I like "category". Renamed.

**Comment by tananaev** [comment]
Looks good, thanks.

**Comment by renaudallard** [comment]
Category is not visible/editable in the web interface, is that expected?

**Comment by Abyss777** [comment]
@renaudallard 
Yes, it is. I'm going to use it to set images for devices. Therefore there will be additional dialog or something.

**Pull request merged**
