### PR TITLE
Fix excel export if timezone of client and server are different

### PR DESCRIPTION
**Pull request by Abyss777**
Have to use second parser because `Ext.Date.format(from, 'c')` format without milliseconds
Parse parameters inside `getExcel()` functions.

Period cell become: `${from.toString("YYYY.MM.dd HH:mm:ss")+" - "+to.toString("YYYY.MM.dd HH:mm:ss")}`

Cells with times become:
`${new("org.joda.time.DateTime", event.serverTime, timezone).toString("YYYY.MM.dd HH:mm:ss")}`

### CODE REVIEW

**Comment by tananaev** [comment]
Why does it not include milliseconds in the time?

**Comment by Abyss777** [comment]
Good question. Frankly, I do not know.
http://docs.sencha.com/extjs/6.0.1/classic/Ext.Date.html it refers to http://fi2.php.net/manual/en/function.date.php that do not contains milliseconds in example.

**Comment by tananaev** [comment]
Can we use `dateTimeParser()` instead of specific formatter? It should be able to handle any ISO format.

**Comment by Abyss777** [comment]
I'll check.

**Comment by Abyss777** [comment]
Used one parser and also reverted parsing to ReportResource.
Result changes should look more consistence.

Not sure, are new indentations in `ReportResource` right?

**Comment by tananaev** [comment]
Merged, looks good to me.

**Pull request merged**
