### PR TITLE
Added speed and course information to the traccar log. This would hel…

### PR DESCRIPTION
**Pull request by asatsi**
Added speed and course information as well to the traccar log. This would help render the track on a different UI. As well this information could be pushed into elasticsearch via logstash for better analytics.

### CODE REVIEW

**Comment by tananaev** [comment]
Why is there an extra comma at the end?

**Comment by tananaev** [comment]
Also, why did you create a new pull request? I think you need to read how to properly do pull request. You should be able to update an old one.

**Comment by asatsi** [comment]
Not very familiar with 'git' yet. Thanks for bearing with me. Please check now and let me know.

**Comment by tananaev** [comment]
Looks good now. Thanks.

**Pull request merged**
