### PR TITLE
added remember me checkbox at login

### PR DESCRIPTION
**Pull request by ninioe**

### CODE REVIEW

**Comment by tananaev** [comment]
Please use extjs references instead of global ids.

**Comment by ninioe** [comment]
Hi Anton,
Can you approve this pull request?

Thanks
Erez

**Comment by tananaev** [comment]
I can, but can you please just do one more thing. Rename references from `txtXxx` to `xxxField`.

**Comment by tananaev** [comment]
Merged, thanks.

**Comment by tananaev** [comment]
I have done some minor refactoring. Can you please stop shortening the words for no reason. That's for future pull request. As for this one, I have tried the feature and the problem is that we still show login dialog. I think we shouldn't. Can you please fix it.

**Comment by ninioe** [comment]
Yes I can, but it will have to wait till Sunday morning

**Comment by tananaev** [comment]
That's fine. It can wait till Sunday. Thanks

**Pull request merged**
