### PR TITLE
With itemclick listener it's possible to jump to the device even if t…

### PR DESCRIPTION
**Pull request by gaborgsomogyi**
…here is only one

### CODE REVIEW

**Comment by tananaev** [comment]
There is a button to center selected object. This seems like workaround other that a correct solution. Also, it's not consistent with the rest of the grids.

**Comment by gaborgsomogyi** [comment]
Should this button should work immediately? As far as I've seen it jumps only if an update comes from the device.

**Comment by tananaev** [comment]
Currently it doesn't, but it makes sense to fix that button to jump immediately.

**Comment by gaborgsomogyi** [comment]
If that would jump immediately then this modification is useless :)

**Comment by tananaev** [comment]
Are you interested in implementing the change?

**Comment by gaborgsomogyi** [comment]
Sure, originally I'm java and C++ dev but I'm sure it's not brain surgery

**Pull request closed without merging**
