### PR TITLE
Add lib for Microsoft JDBC Drivers

### PR DESCRIPTION
**Pull request by CVSz**
Test Server on
Windows Server 2012 R2
MSSQL 2014

### CODE REVIEW

**Comment by tananaev** [comment]
I don't think it's a good idea to include proprietary driver.

Have you actually checked Microsoft terms and conditions to see if it's allowed.

**Comment by Abyss777** [comment]
I'm not sure it is possible to distribute Microsoft JDBC driver in traccar installer at the moment.
According to license 

> Before the transfer, that party must agree that this agreement applies to the transfer and use of the software

user must agree its licence. We do not have such mechanism in installer at the moment.

**Comment by tananaev** [comment]
@CVSz, please comment.

**Comment by CVSz** [comment]
I am consulting friends programming. That can be used or not, and now I'm editing. Some defect

**Comment by CVSz** [comment]
i see maven have repository for ms jdbc driver

        
        <dependency>
            <groupId>com.microsoft</groupId>
            <artifactId>sqljdbc4</artifactId>
            <version>3.0</version>
        </dependency>

**Comment by CVSz** [comment]
i think we can use maven repo for mssql after build source

**Comment by tananaev** [comment]
Agree, but it would be still nice to find out if it's possible to distribute it.

**Pull request closed without merging**
