### PR TITLE
Add email configuration options for geofencing notification.

### PR DESCRIPTION
**Pull request by jenkstom**
Add email settings to config files for geofence notifications.

### CODE REVIEW

**Comment by tananaev** [comment]
I don't think it makes much sense to add those lines because there are no meaningful default values. User still has to configure it manually.

**Comment by jenkstom** [comment]
Could I add them as XML comments? It took me a while to figure out why the notifications weren't working. I had to dig through the source code and I don't know much about Java. It would have been easier if it were in the config file.

**Comment by tananaev** [comment]
You could search on the forum. I also plan to write some official documentation, but I haven't got time to do it yet.

**Comment by tananaev** [comment]
Configuration has been updated:

https://www.traccar.org/configuration-file/

**Pull request closed without merging**
