### PR TITLE
 Secure Connection between GPS Client and Host #1942 

### PR DESCRIPTION
**Pull request by FX7**
This is putting the base in the backend for an extension of the OsmAndProtocol. Now the backend can use the key, stored for a device, to decode an request.

I havent made any extensions in the database scheme, nor any etensions in the server frontend, nor any extension of the client.

I hope with some help, this should become a working part ...

### CODE REVIEW

**Comment by tananaev** [comment]
First of all, code does follow any of the code style requirements. Please run `mvn site` and make sure there are no new issues there.

Secondly, I don't really understand how it works. Does device send both key and encrypted message?

**Comment by ivanfmartinez** [comment]
@tananaev  apparently the Android device send ID unencrypted, and all other data encrypted by the key. 

The server should be updated to have the key in the database. In my mind to use this the cipher type (hardcoded now as AES) should be also in database. Adding two fields to each device can make possible do define encryption type and key to be used and make possible to implement encryption in other protocols too.

The code just works for tests without adding key and creating UI to update the fields in the server side, but I think is a good idea and easy to implement in the server and in Android client at least.

**Comment by FX7** [comment]
Hello and sorry that I may not be so quick responding. I hope to keep my response time in under one week ;-)

> First of all, code does follow any of the code style requirements. Please run mvn site and make sure there are no new issues there.
Im sorry. Maven is really new to me so I have to get into this tool. I will run this and hope I can fix all code issues.

As @ivanfmartinez mentioned: This is just the basic code for the issue. Main thing would be to get the enryption into the client. I think I can try this, but I dont have to much time :/
The idea of making the cipher type optional by device is a really good one. But I think for a first run, this is not essential.

**Comment by tananaev** [comment]
Why not use standard HTTPS connection instead of re-inventing our own encryption?

**Comment by ivanfmartinez** [comment]
@tanaev The https will exchange a lot of data just to stablish the secure connection. Considering that we need just few bytes with location information. I think that is a big overhead. For web browsing, and standard web usage https  the overhead is low, but in this specific topic is very high.

The code does not re-invent it just uses an existing algorithm, which make data secure (if no one get access to the encryption key). And according to Android documentation the cipher is available since level 1 API. The implementation probably will be easy in the Android side.

@FX7 making the cipher configurable make possible to use in different devices, as the java  on server probably have more options than the smaller Android devices.

**Comment by FX7** [comment]
Also https needs lots of stuff to handle with (CAs, self-signed certs, expirering certs ...).
And as @ivanfmartinez said: I dont reinvent stuff, just using std encryption algorithm.

Sorry, that I dindt find time so far for cleaning up the code or even handle the client side. I hope I can do some of the stuff in this week.

**Comment by tananaev** [comment]
I still think HTTPS is a better option. All you need is a certificate (can possibly be self signed, but ideally real one). Connection can be maintained to avoid overhead.

**Comment by ivanfmartinez** [comment]
Lets encrypt make easy to create and maintain valid certificates, its a good solution for future implementations. My traccar server web interface is only accessible using https, using letsencrypt and nginx as reverse proxy.

Using self signed are not necessary. But the client should recognize the certificate authority. New devices accepts lets encrypt, older devices not, and some does not accept to install new root certificates.

How a connection can be maintained in a device that is moving(using different cells, the IP will be changing) and have limited battery ?

I never seen an implementation of SSL/TLS with disconnection and reconnection without negotiation . Do you have any reference to read about this ?

**Comment by tananaev** [comment]
There is no reconnection. That's not how mobile network works.

**Comment by ivanfmartinez** [comment]
In some cases I have seen the device using same IP in different locations, but sometimes the IP has changed (valid one not CGNAT or something like internal ip) in the same place. 

On server side, if the client does not send data for some time the server will disconnect by timeout. 

If is possible to have a single SSL negotiation and use the same connection for long time, without making the device awake to keep connection alive It will be really the best option. I did not know how to do this.

**Comment by FX7** [comment]
Besides that there is some work on the client side to be done for a https connection, whats on the server side and where to "hook in"? How to get a protocol using https and still have access to the webinterface? Or is there already some way to do so?

**Comment by ivanfmartinez** [comment]
On the server side a simple way to do the https is to use an reverse proxy that supports https, if clients support SNI you can share the IP with many apps just using different names. If clients does not support SNI you should have one IP for each SSL certificate.

On client  side if using the standard routines and a trusted certificate, there are no big changes to replace http to https.

Apparently all Android after 4.2 supports SNI for all java applications.

**Comment by FX7** [comment]
I did this for the WebInterface. But can I also do this for the device protocol? But that would mean, I need one domain name for the webinterface like webinterface.tracking.domain and one for the device protocol like protocolX.tracking.domain. And last but not least, I would need a unique name for each protocol, right?

That configuration wouldnt need any server code or configuration changes. With server I mean the traccar server not the configuration of the webserver that is providing the proxy.

On the client side some code extensions have to be made. So that the client can handle https.

Are all my presumptions correct?

**Comment by tananaev** [comment]
You can use ports with HTTPS as well. For example:

https://example.com:5055

Not sure if you can get a real SSL certificate for it though.

**Comment by FX7** [comment]
SSL certificates dont no anything about ports. They are just for a domain.
Only the browser / client coult react to this and say "somethings maybe wrong". But I didnt know about such a "feature".

Ok, back to the point: This way I dont have to make any code changes on the traccar server side, correct? I have to config a proxy webserver to listen to the port and then redirect all traffic to traccar.

But the client has to be extended, to know about https, so there is some coding to do on this side, correct?

**Comment by tananaev** [comment]
Yes, it looks like only Traccar Client has to be modified.

**Comment by ivanfmartinez** [comment]
If the certificate is valid and recognized by the Android device, probably the change will be just make possible to select https intead of hardcoded http.

https://github.com/tananaev/traccar-client-android/blob/master/app/src/main/java/org/traccar/client/ProtocolFormatter.java

**Comment by dschense** [comment]
u think its enough to change:

```
Uri.Builder builder = new Uri.Builder();
        builder.scheme("http").encodedAuthority(address + ':' + port)
```

to

```
Uri.Builder builder = new Uri.Builder();
        builder.scheme("https").encodedAuthority(address + ':' + port)
```

**Comment by tananaev** [comment]
Should be enough.

**Comment by dschense** [comment]
fair enough to try

**Comment by dschense** [comment]
Ive tried this.
I changed the builder sheme to https and build the app.
then set up reverse proxy with nginx from incoming port with ssl to traccar serverport 5055 http.
but this does not work.

**Comment by ivanfmartinez** [comment]
What was exactly the problem ? 

The nginx received the request ? Do you have used a port different of 5055 in nginx  for the SSL service ? 

If nginx did not received the request the problem is on the client. If nginx received the request maybe is a problem with your nginx configuration.

There are any error in Android logcat  ?

**Comment by dschense** [comment]
I dont know yet.

nginx gets nothing. i used port 5550 for incoming and port 5055 for the reverse.

and this is what I get in logcat:

`06-21 16:49:22.490 2511-2511/org.traccar.client I/PositionProvider: provider location
06-21 16:49:22.490 2511-2511/org.traccar.client I/PositionProvider: backup provider stop
06-21 16:49:22.490 2511-2511/org.traccar.client I/PositionProvider: location new
06-21 16:49:22.491 2511-2511/org.traccar.client D/TrackingController: write (id:0 time:1466527762 lat:70.0 lon:6.0)
06-21 16:49:28.269 2511-2511/org.traccar.client D/TrackingController: retry
06-21 16:49:45.290 2511-2511/org.traccar.client I/PositionProvider: provider location
06-21 16:49:45.290 2511-2511/org.traccar.client I/PositionProvider: backup provider stop
06-21 16:49:45.290 2511-2511/org.traccar.client I/PositionProvider: location new
06-21 16:49:45.293 2511-2511/org.traccar.client D/TrackingController: write (id:0 time:1466527785 lat:70.0 lon:6.0)
06-21 16:49:58.274 2511-2511/org.traccar.client D/TrackingController: read
06-21 16:49:58.279 2511-2511/org.traccar.client D/TrackingController: send (id:1 time:1466527027 lat:70.0 lon:6.0)
06-21 16:50:13.354 2511-2511/org.traccar.client D/TrackingController: retry
06-21 16:50:43.364 2511-2511/org.traccar.client D/TrackingController: read
06-21 16:50:43.377 2511-2511/org.traccar.client D/TrackingController: send (id:1 time:1466527027 lat:70.0 lon:6.0)
06-21 16:50:58.460 2511-2511/org.traccar.client D/TrackingController: retry
`

**Comment by ivanfmartinez** [comment]
https://github.com/tananaev/traccar-client-android/blob/master/app/src/main/java/org/traccar/client/RequestManager.java

replace the 
"        } catch (IOException error) {
            return false;"

with 
"        } catch (IOException error) {
            Log.e(RequestManager.class.getSimpleName(), "Request error : "+ request, error);
            return false;"

with this change the error will be at Logcat.

@tananaev this logging can help to detect communication errors in the Android client.

**Comment by FX7** [comment]
Perfect! But if I get it right, you changed the hard coded http to hard coded https, right? I think this should be part of the address thats inputet by the user.
Or maybe try https and if this is not working, use http as fallback?

**Comment by ivanfmartinez** [comment]
@FX7 I think the protocol should be configured and not keep trying the two options without knowing which is correct. That hardcoded change is for testing the concept.

**Comment by FX7** [comment]
You'r completely right. I just mentioned the "try both" method as fallback ;-)

**Comment by dschense** [comment]
yep it is hardcoded by now.
I think its the best to do something like this:

In Client enter adress with full path like http://example.com or https://example.com

and then:

```
if (!url.StartsWith("http://", StringComparison.OrdinalIgnoreCase))
    builder.scheme("http")
    if (!url.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
    builder.scheme("https")
```

or something like this

**Comment by ivanfmartinez** [comment]
@dschense  something like this can be implemented without changing the current UI. 

But for compatibility it should consider the if address starts with "protocol://" use protocol as scheme, else use the standard http scheme.

have you made the test with the Log.e in RequestManager ?
Do you have used an valid certificate on your nginx or an self signed ?

**Comment by dschense** [comment]
@ivanfmartinez 

yes. Ive added the Log.e:

`06-21 18:04:35.257 10790-10790/org.traccar.client I/PositionProvider: location new
06-21 18:04:35.259 10790-10790/org.traccar.client D/TrackingController: write (id:0 time:1466532274 lat:48.0 lon:9.0)
06-21 18:04:35.317 10790-10790/org.traccar.client D/TrackingController: read
06-21 18:04:35.318 10790-10790/org.traccar.client D/TrackingController: send (id:1 time:1466532274 lat:48.0 lon:9.0)
06-21 18:04:35.367 10790-10790/org.traccar.client D/TrackingController: delete (id:1 time:1466532274 lat:48.0 lon:9.0)
06-21 18:04:35.387 10790-10790/org.traccar.client D/TrackingController: read

And I used a valid cert by LetsEncrypt.`

**Comment by ivanfmartinez** [comment]
previous log showed 
send
retry

this log :
send
delete

apparently its working, no error from RequestManager.

**Comment by dschense** [comment]
yep. no error. The fault was i did not open the port in my iptables.

**Comment by FX7** [comment]
I have contacted the developer of the alternative traccar client https://play.google.com/store/apps/details?id=de.wialonconsulting.wiatrack.traccar
He has implemented a https acces and i was lucky to get early access to this version: Its working!

So thank you all, for helping!

I would like to help implementing this in the "official" client, but I dont have to much android coding skills. :/

**Comment by tananaev** [comment]
I will consider implementing HTTPS in official client for one of the next releases.

**Comment by tananaev** [comment]
Closing this pull request.

**Pull request closed without merging**
