### PR TITLE
Changed way of summary distance calculation

### PR DESCRIPTION
**Pull request by Abyss777**
It is small this time

- `DistanceHandler` is always enabled now
- Summary distance is calculated by "odometer" if exist or by "distance" if not

### CODE REVIEW

**Comment by Abyss777** [comment]
Oh, I've forgotten GranitProtocolDecoder sets `Position.KEY_DISTANCE`. What we should do? Remove it from ProtocolDecoder or store in other attribute?

**Comment by tananaev** [comment]
What's distance in Granit protocol? Is it odometer value?

**Comment by Abyss777** [comment]
No, it is distance between current and previous position.

**Comment by tananaev** [comment]
I guess we can ignore it for now. I understand now why you wanted to make distance value to be only distance from last position. Maybe we can save it under some other key, or maybe store total distance under some other key.

**Comment by Abyss777** [comment]
I like an idea to store total distance in other key.
Like `Position.KEY_TOTAL_DISTANCE = "totalDistance"`

`DistanceHandler` will calculate distance between current and last position and store it to `KEY_DISTANCE`  if it is not there already. I mean it won't replace device calculated distance.

Also `DistanceHandler` will sum `KEY_TOTAL_DISTANCE` and `KEY_DISTANCE`

`KEY_DISTANCE` is not very useful in this case but it will be uniform. May be there will be some other protocols that calculates distance by themselves. 

Is this logic fits?

**Comment by tananaev** [comment]
Yes, I think it's a good idea.

**Comment by Abyss777** [comment]
Hm, I've noticed another problem.  Some protocols set 0,0 coordinates to not valid positions (gps not fixed and others)

`KEY_TOTAL_DISTANCE` will rise dramatically for such positions. I suggest calculate distance only between valid positions for not valid it should be zero. 
It will cause loosing some small distances in case: valid-notValid-notValid-valid
but will exclude huge jumps of total distance.

**Comment by tananaev** [comment]
I guess we can put filtering handler before distance calculation to solve this problem.

**Comment by Abyss777** [comment]
Also one reason to not allow user reset total distance, it will cause mistakes in reports.

**Comment by tananaev** [comment]
Is this pull request ready?

**Comment by Abyss777** [comment]
It is look like, but I want test tomorrow on real trips.

**Comment by tananaev** [comment]
OK, let me know how it goes.

**Comment by Abyss777** [comment]
I've noticed the comment https://github.com/tananaev/traccar/blob/master/src/org/traccar/model/Position.java#L22
`"totalDistance"` seems wrong then. Should I use `"total-distance"` ?

**Comment by tananaev** [comment]
Good question. Maybe it's better to change everything to lower-camel-case.

**Comment by Abyss777** [comment]
May be, but it should be done in other pull request. There are a lot of changes in protocols and ObdDecoder and may be in other places.

**Comment by Abyss777** [comment]
Seems done now.
Tested on real device total distance and emulate odometer for test device. Works OK.

**Comment by tananaev** [comment]
Merged, thanks for pull request.

**Pull request merged**
