### PR TITLE
Added a post option to forward url

### PR DESCRIPTION
**Pull request by NateZ7**
Hi Anton,

As we discussed, forward.json will determine if the forward url would be POST or GET.

### CODE REVIEW

**Comment by tananaev** [comment]
Why are you manually create a hash map for JSON object? You need to use existing models.

Also, build failed, so you would need to fix the error before we can proceed.

**Comment by NateZ7** [comment]
Hi Anton,

You asked me to follow the event forwarding logic, so I did.
As I saw in EventForwarder, you created hash map manually.
Let me know if i'm mistaken about that.
Plus, I had some issues with the fork, so please address only the second
fork, which has no build errors (fixed it)

Let me know for any fix needed in order to merge my changes.
Thanks,
Nativ.

**Comment by tananaev** [comment]
You need to use full objects same way as in event forwarding, but not individual primitive types. Please close second pull request.

**Comment by NateZ7** [comment]
Deleted the wrong pull request, and fixed what you asked.

**Pull request closed without merging**
