### PR TITLE
Added ODOMeter and Modification to Mobile UI

### PR DESCRIPTION
**Pull request by amilasilva88**
https://github.com/tananaev/traccar/commit/0350d762a7c08199e79dc401b6c6821d7e2a21bd

### CODE REVIEW

**Comment by tananaev** [comment]
Thanks. I like the implementation, but there a couple of issues:

0. Odometer is a single word, not two. Applies to all names in your code.
1. Please exclude your branding.
2. Use spaces instead of tabs.

**Comment by amilasilva88** [comment]
Thanks for your feedback, can you please check and take my latest modifications

earlier was my mistake, after sending a pull request i have added my branding commit. some how it shows to you in pull request. I removed everything from my source files and committed back. 

thanks
Amila Silva

**Comment by tananaev** [comment]
Tabs and naming issues are still there.

**Comment by amilasilva88** [comment]
"Odometer is a single word, not two. Applies to all names in your code." -
   - I made it to a single word, "Applies to all names in your code" means do you want to add it to all the language files is it?

"Use spaces instead of tabs."
   - how do i identify this?. please let me know which files do i need to do this

**Comment by tananaev** [comment]
I want to change `odoMeter`/`ODOMeter` to `odometer`/`Odometer` in all places (classes, methods, variables etc).

All files should use 4 spaces indention instead of tabs. You can search all files using you IDE (examples is whole `ODOMeterHandler` class and couple of other places).

**Comment by amilasilva88** [comment]
Thanks for guidance. Please check now I have made those requested changes.
Refactoring - tabs to spaces and naming convention
https://github.com/mungingLabs/traccar/commit/a70f478740514e6e60ffbe49906a9c6150b2ec99s

**Comment by tananaev** [comment]
Looks good now. I will try to merge it over the weekend. Thanks.

**Comment by amilasilva88** [comment]
Ok, you are welcome

**Comment by tananaev** [comment]
I have merged the changes, but I've done some modification. The most significant one is that I renamed `odometer` to `distance` and moved it into `other` field.

**Comment by amilasilva88** [comment]
Thanks Anton,

**Pull request merged**
