### PR TITLE
Implement server statistics collection

### PR DESCRIPTION
**Pull request by tananaev**
@Abyss777, can you please review the changes.

For now it creates a record every minute (mostly for testing), but I plan to change it to every day a bit later (before release).

### CODE REVIEW

**Comment by Abyss777** [comment]
Useful feature.
On the first sight everything looks good.
If you wait for tomorrow I will compile and test more carefully.

**Comment by tananaev** [comment]
Thanks. I think it would be useful to have some usage statistics for the server, so decided to implement something simple. In future we can extend it to return data per protocol or something, but general numbers are enough to start with.

**Comment by Abyss777** [comment]
Code works OK, without issues.
But there is some problems in wording or idea.
For example, I started test-generator an look in db, first record is OK, but next has `activeusers` = 0 and `activedevices` = 0. It not looks like true, because device are active and sends positions and me watching on toasts in web-client.

Just an suggestion, may be better use `ConnectionManager`.`activeDevices` and `ConnectionManager`.`listeners`?

**Comment by Abyss777** [comment]
But I just thought if we change the period to day, your variant will be more relevant.

**Comment by tananaev** [comment]
You are right about zero values. Especially it's important for device, if one has been sending for more than a day, it won't be counted as active because there would be no new "identification".

I have changed the logic. It's more heavy because it will check devices list on every message, but it's more accurate. I also changed it to daily record. Can you please check quickly and then I'll merge it.

**Comment by Abyss777** [comment]
It work OK without issues and more accurate now. But ...
I've replaced interval back to minute for test. And got strange fluctuation two times.
`mesagereceived` and `messagestored` are lost two times. I gues it can be more on many devices.
image



My suggestion, the reason is synchronization/multi-threading

**Comment by tananaev** [comment]
Merging it for now.

I think what you are looking at is not a statistics issue. The problem is that script that generates data doesn't actually send in exact 1 second interval. There is some delay to send data, so it accumulates and sometimes it can get through only 59 messages instead of 60.

**Pull request merged**
