### PR TITLE
Convert speed units in mail notifications

### PR DESCRIPTION
**Pull request by Abyss777**
- Added speed converting in NotificationFormatter
- Used constants in UnitsConverter

Partially fix https://www.traccar.org/forums/topic/setting-the-speed-limit-and-speed-limit-notifications/

### CODE REVIEW

**Comment by Abyss777** [comment]
Any comments for this pull request?

**Comment by tananaev** [comment]
Weird, I'm pretty sure I've added a comment. Maybe there was some network issue and it wasn't published. Anyway, the only comment I has is that querying the users table every time might not be a very good idea. Possibly we need to cache it same as with devices.

**Comment by Abyss777** [comment]
Totally agree.
I suggest cache it in `PermissionManager` because it is already cached there but do not have public interface.

**Comment by Abyss777** [comment]
Sorry, I occasionally delete branch, I will reopen it after implementing cache.

**Comment by Abyss777** [comment]
Oh, again I've broken git. I'll made a new pull request.

**Pull request closed without merging**
