### PR TITLE
make methods accessible to ther classes

### PR DESCRIPTION
**Pull request by ivanfmartinez**
Other classes can use the formatter, if this two methods are public.

### CODE REVIEW

**Comment by tananaev** [comment]
What other classes?

**Comment by ivanfmartinez** [comment]
I'm migrating my classes  that used an PositionUtil  class that does not have merge accepted. #1601 

Making this methods public any class can use this code for template processing ( in my case classes called from extra.handlers configuration ).

I'm moving my code to use the new features that are included in traccar base code like this template processing and geofences.

**Comment by tananaev** [comment]
If we want to use those methods in some other classes, it would probably make sense to move them out of "notification" class.

**Comment by ivanfmartinez** [comment]
my code is doing notification, just using different methods, and using the same template process will be good and will make easier to move later my code directly inside traccar.

I think that maybe the sms method can be split to be more generic and permit other notification types that are just single string template processing like SMS.

**Comment by tananaev** [comment]
Merged, thanks.

**Pull request merged**
